server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456Ben
    url: jdbc:mysql://alicloud:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:mybatis-config.xml